### ISSUE TITLE
missing PyQt5 modules using PyQt5 5.9.2 and Qt5 5.8.0

### ISSUE THREAD

**Issue by boegel** [spyder-ide/qtpy#137]
When trying to run `Spyder` installed on top of PyQt5 5.9.2 and Qt5 5.8.0, I'm running into errors as mentioned below.

`QtWebKit ` was removed in Qt5 5.6.0, see http://wiki.qt.io/New_Features_in_Qt_5.6#Removed_Modules

What's the recommended workaround/fix for this (other than using an older version of `Qt5`)?

```
$ spyder3
Traceback (most recent call last):
  File "/apps/Spyder/3.2.5-intel-2017b-Python-3.6.3/lib/python3.6/site-packages/QtPy-1.3.1-py3.6.egg/qtpy/QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/apps/Spyder/3.2.5-intel-2017b-Python-3.6.3/bin/spyder3", line 3, in <module>
    start.main()
  File "/apps/Spyder/3.2.5-intel-2017b-Python-3.6.3/lib/python3.6/site-packages/spyder/app/start.py", line 144, in main
    from spyder.app import mainwindow
  File "/apps/Spyder/3.2.5-intel-2017b-Python-3.6.3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/apps/Spyder/3.2.5-intel-2017b-Python-3.6.3/lib/python3.6/site-packages/QtPy-1.3.1-py3.6.egg/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'
```

**Comment by ccordoba12** [comment]
You need either QtWebKit or QtWebEngine to run Spyder. It seems you have none of them.

**Comment by boegel** [comment]
@ccordoba12 Any idea whether QtWebEngine is supposed to be part of Qt5 (by default)? Trying to figure out what's wrong...

**Comment by ccordoba12** [comment]
It is by default. Closing this one because it's an installation problem in your side and it has nothing to do with qtpy.
