### ISSUE TITLE
ValueError: API 'QString' has already been set to version 1 at line 141 in __init__.py file.

### ISSUE THREAD

**Issue by kailunfan** [spyder-ide/qtpy#144]
```
  File "D:\program\python2.7\lib\site-packages\qtpy\__init__.py", line 141, in <module>
    sip.setapi('QString', 2)
ValueError: API 'QString' has already been set to version 1
```
Everything is OK after I  alter ```except AttributeError:``` to ```except ValueError:``` .

Pls: It is happend on PyQt4 (4.11.4).

**Comment by kailunfan** [comment]
Sorry for my vague expressions. It happens like this.
```bash
>>> from PyQt4 import QtGui
>>> import qtawesome
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\program\python2.7\lib\site-packages\qtawesome\__init__.py", line 19, in <module>
    from .iconic_font import IconicFont, set_global_defaults
  File "D:\program\python2.7\lib\site-packages\qtawesome\iconic_font.py", line 24, in <module>
    from qtpy.QtCore import QObject, QPoint, QRect, qRound, Qt
  File "D:\program\python2.7\lib\site-packages\qtpy\__init__.py", line 141, in <module>
    sip.setapi('QString', 2)
ValueError: API 'QString' has already been set to version 1
>>>
```

**Comment by ccordoba12** [comment]
I see what you mean now. I'll fix this for our 1.4.2 version.
