### ISSUE TITLE
upgrading qtpy from 1.1.2 to 1.2.0 breaks spyder with qt4

### ISSUE THREAD

**Issue by mfernezir** [spyder-ide/qtpy#95]
If I do pip install -U qtpy, spyder crashes with the following message:

> Traceback (most recent call last):
  File "/home/developer/.virtualenvs/dev3/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 3001, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/developer/.virtualenvs/dev3/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 2905, in run_spyder
    main.setup()
  File "/home/developer/.virtualenvs/dev3/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 869, in setup
    self.projects = Projects(self)
  File "/home/developer/.virtualenvs/dev3/lib/python3.5/site-packages/spyder/plugins/projects.py", line 71, in __init__
    self.setup_project(self.get_active_project_path())
  File "/home/developer/.virtualenvs/dev3/lib/python3.5/site-packages/spyder/widgets/projects/explorer.py", line 226, in setup_project
    show_all=self.show_all)
  File "/home/developer/.virtualenvs/dev3/lib/python3.5/site-packages/spyder/widgets/explorer.py", line 195, in setup
    self.common_actions = self.setup_common_actions()
  File "/home/developer/.virtualenvs/dev3/lib/python3.5/site-packages/spyder/widgets/projects/explorer.py", line 55, in setup_common_actions
    self.toggle_hscrollbar(self.show_hscrollbar)
  File "/home/developer/.virtualenvs/dev3/lib/python3.5/site-packages/spyder/widgets/projects/explorer.py", line 70, in toggle_hscrollbar
    self.header().setResizeMode(QHeaderView.ResizeToContents)
  File "/home/developer/.virtualenvs/dev3/lib/python3.5/site-packages/qtpy/_patch/qheaderview.py", line 83, in setResizeMode
    raise Exception('setResizeMode is only available in Qt4. Use '
Exception: setResizeMode is only available in Qt4. Use setSectionResizeMode instead.

If I revert with pip install qtpy==1.1.2, Spyder starts normally.

System and Qt4 info:
Ubuntu 16.04, Python 3.5.2, Qt 4.8.7, PyQt 4.11.4, SIP 4.18.1

I am using Spyder 3.0.2.

**Comment by ccordoba12** [comment]
This has to be fixed in Spyder, not here. Could you reopen this same bug in the Spyder repo please? Thanks :-)

**Comment by mfernezir** [comment]
Ok :)
